apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: "1.0"
  template:
    metadata:
      labels:
        app: app
        version: "1.0"
    spec:
      containers:
      - name: hello
        image: laclac0901/hi:1.0
        ports:
        - containerPort: 80
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
