apiVersion: v1
kind: Service
metadata:
  name: app
  # labels:
  #   run: app
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: app
    version: "ID"
    # run: app
  