version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:

  build-docker-blue: 
    parameters:
      docker_image:
        type: string
        default: 'laclac0901/hello:1.0'
    version:
      - type: string
      - default: 'BLUE'
    working_directory: ~/blue-green-test
    steps:
      - checkout
      - run: 
          name: create main.py file
          command: |
            cat main-test.py | sed "s|ID|<< parameters.version >>|g" > main.py
      - run: 
          name: Test result
          command: |
            ls
            cat main.py
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t << parameters.docker_image >> .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push << parameters.docker_image >>



workflows:
  default:
    jobs:
      # - lint
      # - build-docker-blue
      # - deploy-k8s:
      #     requires: 
      #       - build-docker